# Generated by Django 2.0.7 on 2019-09-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagares', '0005_auto_20190908_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagareventa',
            name='fecha_emitido',
            field=models.DateField(),
        ),
    ]
