# Generated by Django 2.0.7 on 2019-07-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0001_initial'),
        ('productos', '0002_auto_20190626_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='titular',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='titulares.Titular'),
            preserve_default=False,
        ),
    ]
