# Generated by Django 2.0.7 on 2019-07-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_compra_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[['PAGARE', 'Pagare'], ['TRANSFERENCIA', 'Transferencia']], default='TRANSFERENCIA', max_length=9, verbose_name='Forma de Pago')),
            ],
        ),
    ]
