# Generated by Django 2.1.2 on 2019-07-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.FormaPago'),
        ),
    ]
