# Generated by Django 2.1.2 on 2019-07-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_compra_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='forma_pago',
        ),
        migrations.DeleteModel(
            name='FormaPago',
        ),
    ]
