# Generated by Django 2.0.7 on 2019-08-01 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_compra_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='forma_pago',
            field=models.CharField(choices=[['PAGARE', 'Pagare'], ['TRANSFERENCIA', 'Transferencia']], default='TRANSFERENCIA', max_length=50, verbose_name='Forma de Pago'),
        ),
    ]
