# Generated by Django 2.0.7 on 2019-08-06 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_auto_20190801_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('impuesto1', models.IntegerField()),
                ('impuesto2', models.IntegerField()),
                ('se_calcula_con', models.CharField(choices=[['BASE', 'Base'], ['TOTAL', 'Total']], default='BASE', max_length=50, verbose_name='Valor con el que se calcula')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='lfact',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='nfact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='impuestos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productos.Impuestos'),
            preserve_default=False,
        ),
    ]
