# Generated by Django 2.0.7 on 2019-08-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20190806_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos',
            name='impuesto2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impuestos',
            name='se_calcula_con',
            field=models.CharField(blank=True, choices=[['BASE', 'Base'], ['TOTAL', 'Total']], default='BASE', max_length=50, null=True, verbose_name='Valor con el que se calcula impuesto 2'),
        ),
    ]
