# Generated by Django 2.0.7 on 2019-08-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20190814_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='lote',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
