# Generated by Django 2.0.7 on 2019-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_auto_20190819_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='lote',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
