# Generated by Django 2.0.7 on 2019-08-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_detalleventa_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='lote',
            new_name='lote_heredado',
        ),
    ]
