# Generated by Django 2.0.7 on 2019-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_historico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='lote',
            new_name='lote_heredado',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='lote_heredado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historico',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
