# Generated by Django 2.2.1 on 2020-10-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_auto_20190820_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
    ]
