# Generated by Django 2.0.7 on 2019-09-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoeco',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='certificadoeco',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='certificadoeco',
            name='nombre',
        ),
        migrations.AddField(
            model_name='certificadoeco',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Observaciones_eco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificadoeco',
            name='proveedor_certificado',
            field=models.CharField(max_length=150, verbose_name='Organismo de Certificación y Control'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='certificado_eco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.CertificadoEco', verbose_name='Certificado Ecologico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=11, unique=True, verbose_name='DNI/CIF'),
        ),
    ]
