# Generated by Django 2.0.7 on 2019-09-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20190908_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificadoeco',
            old_name='proveedor_certificado',
            new_name='entidad_certificadora',
        ),
    ]
