# Generated by Django 2.0.7 on 2019-09-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20190908_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadCertificadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=' Organismo de Certificación y Control')),
                ('Observaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Observaciones_eco',
            new_name='observaciones_eco',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='certificado_eco',
        ),
        migrations.DeleteModel(
            name='CertificadoEco',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='entidad_certificadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.EntidadCertificadora'),
        ),
    ]
