# Generated by Django 2.2.1 on 2020-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_auto_20200715_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=11, verbose_name='DNI/CIF'),
        ),
    ]
